### ISSUE TITLE
Remove unused libraries

### ISSUE THREAD

**Issue by juhitiwari** [AASF-IIITM/gladiator#3]
You might find some third-party libraries that are not being used, please remove them both from imports as well as from the project

**Comment by dawksh** [comment]
Can I take this up?

**Comment by juhitiwari** [comment]
> Can I take this up?

Hey @DevDaksh sure you can take this up. Raise a PR once the hacktoberfest starts so that you have one for the hacktoberfest. Till then you can get acquainted with the codebase. Do ask questions if you have any doubts

**Comment by dawksh** [comment]
great!

**Comment by dawksh** [comment]
Should I also remove commented code and unused functions as well?

**Comment by juhitiwari** [comment]
> Should I also remove commented code and unused functions as well?

That will be the part of #2  issue. We have added that one for iiitm students only as we got so many responses from outside iiitm. But feel free to take this issue up! Sorry for the inconvenience. Also, if you find any bugs or any feature improvement do raise an issue :)

**Comment by dawksh** [comment]
I've done it, I'll make the PR in next couple of hours.
